#!/usr/bin/env bash
# generate-live-docs.sh — Fetch docs-content.ts from main branch and create
# a live-docs-content.ts wrapper so preview deploys can show both the PR's
# docs and the current production (main) docs side by side.
#
# Usage: scripts/generate-live-docs.sh
#
# Requires: git with access to origin/main

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

DOCS_CONTENT_PATH="packages/ui/src/components/docs/docs-content.ts"
GENERATED_FILE="$REPO_ROOT/packages/ui/src/components/docs/_main-branch-docs.ts"
WRAPPER_FILE="$REPO_ROOT/packages/ui/src/components/docs/live-docs-content.ts"

echo "Fetching docs-content.ts from origin/main..."

# Ensure we have the main branch ref
git fetch origin main --depth=1 2>/dev/null || {
  echo "WARNING: Could not fetch origin/main. Live docs will not be available."
  exit 0
}

# Extract the file from main branch
if ! git show "origin/main:${DOCS_CONTENT_PATH}" > "$GENERATED_FILE" 2>/dev/null; then
  echo "WARNING: docs-content.ts not found on origin/main. Live docs will not be available."
  rm -f "$GENERATED_FILE"
  exit 0
fi

echo "Generated _main-branch-docs.ts from origin/main"

# Create the wrapper that re-exports with LIVE_ prefixes
cat > "$WRAPPER_FILE" << 'EOF'
// AUTO-GENERATED — DO NOT EDIT
// This file was generated by scripts/generate-live-docs.sh during a preview build.
// It re-exports documentation content from the main branch as "Live Docs".

export { DOCS_PAGES as LIVE_DOCS_PAGES } from './_main-branch-docs.js';
export { DOCS_CONTENT as LIVE_DOCS_CONTENT } from './_main-branch-docs.js';
export { getDocsSourceUrl as getLiveDocsSourceUrl } from './_main-branch-docs.js';

import { DOCS_CONTENT, DOCS_SPACE_INFO } from './_main-branch-docs.js';

// Use our own resolver instead of re-exporting main's, because main's version
// may use document.baseURI which breaks with pushState navigation.
// Vite replaces the literal import.meta.env.BASE_URL at build time.
function getBaseUrl(): string {
  const base = import.meta.env.BASE_URL ?? '/';
  return base.endsWith('/') ? base : base + '/';
}
export function resolveLiveDocsContent(content: string): string {
  return content.replace(/\{\{base\}\}/g, getBaseUrl());
}

export const LIVE_DOCS_AVAILABLE = true;

export const LIVE_DOCS_SPACE_INFO = {
  ...DOCS_SPACE_INFO,
  id: 'cept-live-docs',
  name: 'Docs (Live)',
  source: 'Git (github.com/nsheaps/cept, main branch, read-only)',
  pageCount: Object.keys(DOCS_CONTENT).length,
  contentSize: Object.values(DOCS_CONTENT).reduce((sum, c) => sum + c.length, 0),
};
EOF

echo "Generated live-docs-content.ts wrapper"
echo "Live docs will be available in the preview build."
