name: Lint

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install mise
        uses: jdx/mise-action@v4

      - name: Install dependencies
        run: mise run install

      - name: Lint
        run: mise run lint
