name: Typecheck

on:
  workflow_call:

jobs:
  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install mise
        uses: jdx/mise-action@v4

      - name: Install dependencies
        run: mise run install

      - name: Typecheck
        run: mise run typecheck
